export default {
  status: 'ok',
  status_message: 'Query was successful',
  data: {
    movie_count: 37671,
    limit: 20,
    page_number: 1,
    movies: [
      {
        id: 38448,
        url: 'https://yts.mx/movies/thani-oruvan-2015',
        imdb_code: 'tt4987556',
        title: 'Thani Oruvan',
        title_english: 'Thani Oruvan',
        title_long: 'Thani Oruvan (2015)',
        slug: 'thani-oruvan-2015',
        year: 2015,
        rating: 8.4,
        runtime: 160,
        genres: ['Action', 'Crime', 'Thriller'],
        summary:
          'Thoroughly frustrated with Industrialists and Politicians ruining the nation by denying the availability of cheap medicines, IPS officer Mithran is on a self-conceived quest to find the head of this medicine-mafia to channel all his anger towards him. But the ultimate villain, Siddharth Abhimanyu, who is also a decorated Scientist proves to be a ruthless and indomitable adversary. —PipingHotViews',
        description_full:
          'Thoroughly frustrated with Industrialists and Politicians ruining the nation by denying the availability of cheap medicines, IPS officer Mithran is on a self-conceived quest to find the head of this medicine-mafia to channel all his anger towards him. But the ultimate villain, Siddharth Abhimanyu, who is also a decorated Scientist proves to be a ruthless and indomitable adversary. —PipingHotViews',
        synopsis:
          'Thoroughly frustrated with Industrialists and Politicians ruining the nation by denying the availability of cheap medicines, IPS officer Mithran is on a self-conceived quest to find the head of this medicine-mafia to channel all his anger towards him. But the ultimate villain, Siddharth Abhimanyu, who is also a decorated Scientist proves to be a ruthless and indomitable adversary. —PipingHotViews',
        yt_trailer_code: 'r5Lih8rKd6k',
        language: 'ta',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/thani_oruvan_2015/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/thani_oruvan_2015/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/thani_oruvan_2015/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/thani_oruvan_2015/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/thani_oruvan_2015/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/D767A8A573EE0E7DFB67C5F4D265F8B48FDE3ED7',
            hash: 'D767A8A573EE0E7DFB67C5F4D265F8B48FDE3ED7',
            quality: '720p',
            type: 'web',
            seeds: 0,
            peers: 0,
            size: '956.31 MB',
            size_bytes: 1002763715,
            date_uploaded: '2021-12-10 22:46:13',
            date_uploaded_unix: 1639172773,
          },
          {
            url: 'https://yts.mx/torrent/download/34AE656B56D02086DCE9B4E9287EB9C1688EEA0B',
            hash: '34AE656B56D02086DCE9B4E9287EB9C1688EEA0B',
            quality: '1080p',
            type: 'web',
            seeds: 30,
            peers: 26,
            size: '1.92 GB',
            size_bytes: 2061584302,
            date_uploaded: '2021-12-10 23:45:39',
            date_uploaded_unix: 1639176339,
          },
        ],
        date_uploaded: '2021-12-10 22:46:13',
        date_uploaded_unix: 1639172773,
      },
      {
        id: 38447,
        url: 'https://yts.mx/movies/back-to-the-outback-2021',
        imdb_code: 'tt13575806',
        title: 'Back to the Outback',
        title_english: 'Back to the Outback',
        title_long: 'Back to the Outback (2021)',
        slug: 'back-to-the-outback-2021',
        year: 2021,
        rating: 7.6,
        runtime: 95,
        genres: ['Adventure', 'Animation', 'Comedy'],
        summary:
          "Tired of being locked in a reptile house where humans gawk at them like they're monsters, a ragtag group of Australia's deadliest creatures plot a daring escape from their zoo to the Outback, a place where they'll fit in without being judged for their scales and fangs. Leading the group is Maddie, a poisonous snake with a heart of gold, who bands together with a self-assured Thorny Devil lizard Zoe, a lovelorn hairy spider Frank, and a sensitive scorpion Nigel. But when their nemesis Pretty Boy, a cute but obnoxious koala unexpectedly joins their escape, Maddie and the gang have no choice but to take him with them. So begins a hair-raising and hilarious road trip across Australia, as they are pursued by a zookeeper Chaz and his adventure-seeking mini-me.",
        description_full:
          "Tired of being locked in a reptile house where humans gawk at them like they're monsters, a ragtag group of Australia's deadliest creatures plot a daring escape from their zoo to the Outback, a place where they'll fit in without being judged for their scales and fangs. Leading the group is Maddie, a poisonous snake with a heart of gold, who bands together with a self-assured Thorny Devil lizard Zoe, a lovelorn hairy spider Frank, and a sensitive scorpion Nigel. But when their nemesis Pretty Boy, a cute but obnoxious koala unexpectedly joins their escape, Maddie and the gang have no choice but to take him with them. So begins a hair-raising and hilarious road trip across Australia, as they are pursued by a zookeeper Chaz and his adventure-seeking mini-me.",
        synopsis:
          "Tired of being locked in a reptile house where humans gawk at them like they're monsters, a ragtag group of Australia's deadliest creatures plot a daring escape from their zoo to the Outback, a place where they'll fit in without being judged for their scales and fangs. Leading the group is Maddie, a poisonous snake with a heart of gold, who bands together with a self-assured Thorny Devil lizard Zoe, a lovelorn hairy spider Frank, and a sensitive scorpion Nigel. But when their nemesis Pretty Boy, a cute but obnoxious koala unexpectedly joins their escape, Maddie and the gang have no choice but to take him with them. So begins a hair-raising and hilarious road trip across Australia, as they are pursued by a zookeeper Chaz and his adventure-seeking mini-me.",
        yt_trailer_code: 'sw4fv74Mx2w',
        language: 'en',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/back_to_the_outback_2021/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/back_to_the_outback_2021/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/back_to_the_outback_2021/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/back_to_the_outback_2021/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/back_to_the_outback_2021/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/8D097DB922768A66C95DF50E0FD1126E80B1DB52',
            hash: '8D097DB922768A66C95DF50E0FD1126E80B1DB52',
            quality: '720p',
            type: 'web',
            seeds: 0,
            peers: 0,
            size: '876.97 MB',
            size_bytes: 919569695,
            date_uploaded: '2021-12-10 22:47:19',
            date_uploaded_unix: 1639172839,
          },
          {
            url: 'https://yts.mx/torrent/download/BE54459375E7A77E3D0AE5C71F99397D512FB2FB',
            hash: 'BE54459375E7A77E3D0AE5C71F99397D512FB2FB',
            quality: '1080p',
            type: 'web',
            seeds: 0,
            peers: 0,
            size: '1.76 GB',
            size_bytes: 1889785610,
            date_uploaded: '2021-12-10 23:47:38',
            date_uploaded_unix: 1639176458,
          },
        ],
        date_uploaded: '2021-12-10 22:47:19',
        date_uploaded_unix: 1639172839,
      },
      {
        id: 38446,
        url: 'https://yts.mx/movies/hurt-2018',
        imdb_code: 'tt6877562',
        title: 'Hurt',
        title_english: 'Hurt',
        title_long: 'Hurt (2018)',
        slug: 'hurt-2018',
        year: 2018,
        rating: 6.8,
        runtime: 93,
        genres: ['Drama', 'Horror', 'Mystery'],
        summary:
          "A peaceful sky, wind in the trees, a ladybug sitting on a blade of wheat. Nothing happens in New Caney, Texas. On Halloween night, the picture-perfect Americana of this farming town is quiet, and remains undisturbed. Time moves painfully slowly. Rose sits by herself, smoking a cigarette, scaring the kids away. She wears a mask, like so many others that night. With her husband, freshly back from the war, Rose is off to the village's annual horror show and things take a dark turn.",
        description_full:
          "A peaceful sky, wind in the trees, a ladybug sitting on a blade of wheat. Nothing happens in New Caney, Texas. On Halloween night, the picture-perfect Americana of this farming town is quiet, and remains undisturbed. Time moves painfully slowly. Rose sits by herself, smoking a cigarette, scaring the kids away. She wears a mask, like so many others that night. With her husband, freshly back from the war, Rose is off to the village's annual horror show and things take a dark turn.",
        synopsis:
          "A peaceful sky, wind in the trees, a ladybug sitting on a blade of wheat. Nothing happens in New Caney, Texas. On Halloween night, the picture-perfect Americana of this farming town is quiet, and remains undisturbed. Time moves painfully slowly. Rose sits by herself, smoking a cigarette, scaring the kids away. She wears a mask, like so many others that night. With her husband, freshly back from the war, Rose is off to the village's annual horror show and things take a dark turn.",
        yt_trailer_code: '',
        language: 'en',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/hurt_2018/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/hurt_2018/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/hurt_2018/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/hurt_2018/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/hurt_2018/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/8C906072B063841A9DC67D0E6C0C036BBE1A5495',
            hash: '8C906072B063841A9DC67D0E6C0C036BBE1A5495',
            quality: '720p',
            type: 'web',
            seeds: 0,
            peers: 0,
            size: '836.89 MB',
            size_bytes: 877542769,
            date_uploaded: '2021-12-10 22:44:55',
            date_uploaded_unix: 1639172695,
          },
          {
            url: 'https://yts.mx/torrent/download/6ABFBB829C7E61A8400F5BB992E5186639D6BBBD',
            hash: '6ABFBB829C7E61A8400F5BB992E5186639D6BBBD',
            quality: '1080p',
            type: 'web',
            seeds: 168,
            peers: 71,
            size: '1.68 GB',
            size_bytes: 1803886264,
            date_uploaded: '2021-12-10 23:41:48',
            date_uploaded_unix: 1639176108,
          },
        ],
        date_uploaded: '2021-12-10 22:44:55',
        date_uploaded_unix: 1639172695,
      },
      {
        id: 38445,
        url: 'https://yts.mx/movies/fascism-on-a-thread-the-strange-story-of-nazisploitation-cinema-2019',
        imdb_code: 'tt10738468',
        title:
          'Fascism on a Thread- The Strange Story of Nazisploitation Cinema',
        title_english:
          'Fascism on a Thread- The Strange Story of Nazisploitation Cinema',
        title_long:
          'Fascism on a Thread- The Strange Story of Nazisploitation Cinema (2019)',
        slug: 'fascism-on-a-thread-the-strange-story-of-nazisploitation-cinema-2019',
        year: 2019,
        rating: 7.1,
        runtime: 91,
        genres: ['Documentary'],
        summary:
          'A look at the ideas and people that was involved in the naziploitations movies.',
        description_full:
          'A look at the ideas and people that was involved in the naziploitations movies.',
        synopsis:
          'A look at the ideas and people that was involved in the naziploitations movies.',
        yt_trailer_code: '',
        language: 'en',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/fascism_on_a_thread_the_strange_story_of_nazisploitation_cinema_2019/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/fascism_on_a_thread_the_strange_story_of_nazisploitation_cinema_2019/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/fascism_on_a_thread_the_strange_story_of_nazisploitation_cinema_2019/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/fascism_on_a_thread_the_strange_story_of_nazisploitation_cinema_2019/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/fascism_on_a_thread_the_strange_story_of_nazisploitation_cinema_2019/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/D2D1A0D9504230437600DEE7BBDA43612703740E',
            hash: 'D2D1A0D9504230437600DEE7BBDA43612703740E',
            quality: '720p',
            type: 'bluray',
            seeds: 0,
            peers: 0,
            size: '840.85 MB',
            size_bytes: 881695130,
            date_uploaded: '2021-12-10 22:44:54',
            date_uploaded_unix: 1639172694,
          },
          {
            url: 'https://yts.mx/torrent/download/0479B56B24441EAB3888D3AF90566074C8B62938',
            hash: '0479B56B24441EAB3888D3AF90566074C8B62938',
            quality: '1080p',
            type: 'bluray',
            seeds: 39,
            peers: 101,
            size: '1.52 GB',
            size_bytes: 1632087572,
            date_uploaded: '2021-12-10 23:43:04',
            date_uploaded_unix: 1639176184,
          },
        ],
        date_uploaded: '2021-12-10 22:44:54',
        date_uploaded_unix: 1639172694,
      },
      {
        id: 38442,
        url: 'https://yts.mx/movies/two-2021',
        imdb_code: 'tt12358104',
        title: 'Two',
        title_english: 'Two',
        title_long: 'Two (2021)',
        slug: 'two-2021',
        year: 2021,
        rating: 4.2,
        runtime: 70,
        genres: ['Drama', 'Mystery', 'Thriller'],
        summary:
          'Two people, a man and a woman, wake up naked and with their abdomens attached to each other.',
        description_full:
          'Two people, a man and a woman, wake up naked and with their abdomens attached to each other.',
        synopsis:
          'Two people, a man and a woman, wake up naked and with their abdomens attached to each other.',
        yt_trailer_code: '',
        language: 'es',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/two_2021/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/two_2021/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/two_2021/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/two_2021/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/two_2021/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/1AB9D5764976270CFFF8130E784D2A0C4E0CF1C3',
            hash: '1AB9D5764976270CFFF8130E784D2A0C4E0CF1C3',
            quality: '720p',
            type: 'web',
            seeds: 132,
            peers: 80,
            size: '655.03 MB',
            size_bytes: 686848737,
            date_uploaded: '2021-12-10 12:59:39',
            date_uploaded_unix: 1639137579,
          },
          {
            url: 'https://yts.mx/torrent/download/98155889576F1C7387D5B138C660651196E86C6A',
            hash: '98155889576F1C7387D5B138C660651196E86C6A',
            quality: '1080p',
            type: 'web',
            seeds: 128,
            peers: 47,
            size: '1.31 GB',
            size_bytes: 1406601789,
            date_uploaded: '2021-12-10 13:46:23',
            date_uploaded_unix: 1639140383,
          },
        ],
        date_uploaded: '2021-12-10 12:59:39',
        date_uploaded_unix: 1639137579,
      },
      {
        id: 38443,
        url: 'https://yts.mx/movies/anonymously-yours-2021',
        imdb_code: 'tt16088568',
        title: 'Anonymously Yours',
        title_english: 'Anonymously Yours',
        title_long: 'Anonymously Yours (2021)',
        slug: 'anonymously-yours-2021',
        year: 2021,
        rating: 6.5,
        runtime: 100,
        genres: ['Drama', 'Romance'],
        summary:
          "After an accidental text message turns into a digital friendship, Vale and Alex start crushing on each other without realizing they've met in real life.",
        description_full:
          "After an accidental text message turns into a digital friendship, Vale and Alex start crushing on each other without realizing they've met in real life.",
        synopsis:
          "After an accidental text message turns into a digital friendship, Vale and Alex start crushing on each other without realizing they've met in real life.",
        yt_trailer_code: '',
        language: 'es',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/anonymously_yours_2021/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/anonymously_yours_2021/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/anonymously_yours_2021/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/anonymously_yours_2021/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/anonymously_yours_2021/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/8A27AF11E9E364ED7A7B59BEA49BB28F14BB5374',
            hash: '8A27AF11E9E364ED7A7B59BEA49BB28F14BB5374',
            quality: '720p',
            type: 'web',
            seeds: 0,
            peers: 0,
            size: '933.26 MB',
            size_bytes: 978594038,
            date_uploaded: '2021-12-10 10:23:25',
            date_uploaded_unix: 1639128205,
          },
          {
            url: 'https://yts.mx/torrent/download/E08D86609F7C6D9CB8F7DF1612697E6D7195BA88',
            hash: 'E08D86609F7C6D9CB8F7DF1612697E6D7195BA88',
            quality: '1080p',
            type: 'web',
            seeds: 0,
            peers: 0,
            size: '1.87 GB',
            size_bytes: 2007897211,
            date_uploaded: '2021-12-10 11:18:12',
            date_uploaded_unix: 1639131492,
          },
        ],
        date_uploaded: '2021-12-10 10:23:25',
        date_uploaded_unix: 1639128205,
      },
      {
        id: 38441,
        url: 'https://yts.mx/movies/the-unforgivable-2021',
        imdb_code: 'tt11233960',
        title: 'The Unforgivable',
        title_english: 'The Unforgivable',
        title_long: 'The Unforgivable (2021)',
        slug: 'the-unforgivable-2021',
        year: 2021,
        rating: 7,
        runtime: 112,
        genres: ['Crime', 'Drama'],
        summary:
          'Released from prison after serving a sentence for a violent crime, Ruth Slater (Bullock) re-enters a society that refuses to forgive her past. Facing severe judgment from the place she once called home, her only hope for redemption is finding the estranged younger sister she was forced to leave behind.',
        description_full:
          'Released from prison after serving a sentence for a violent crime, Ruth Slater (Bullock) re-enters a society that refuses to forgive her past. Facing severe judgment from the place she once called home, her only hope for redemption is finding the estranged younger sister she was forced to leave behind.',
        synopsis:
          'Released from prison after serving a sentence for a violent crime, Ruth Slater (Bullock) re-enters a society that refuses to forgive her past. Facing severe judgment from the place she once called home, her only hope for redemption is finding the estranged younger sister she was forced to leave behind.',
        yt_trailer_code: 'JNUjx7LZoiU',
        language: 'en',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/the_unforgivable_2021/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/the_unforgivable_2021/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/the_unforgivable_2021/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/the_unforgivable_2021/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/the_unforgivable_2021/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/E68EE3FC711024F89D37F539A404F3211F326F97',
            hash: 'E68EE3FC711024F89D37F539A404F3211F326F97',
            quality: '720p',
            type: 'web',
            seeds: 0,
            peers: 0,
            size: '1.02 GB',
            size_bytes: 1095216660,
            date_uploaded: '2021-12-11 01:15:05',
            date_uploaded_unix: 1639181705,
          },
          {
            url: 'https://yts.mx/torrent/download/9D81813D0E148CF9C88DF15D3A417EA1EDD5C4C1',
            hash: '9D81813D0E148CF9C88DF15D3A417EA1EDD5C4C1',
            quality: '1080p',
            type: 'web',
            seeds: 0,
            peers: 0,
            size: '2.1 GB',
            size_bytes: 2254857830,
            date_uploaded: '2021-12-11 04:22:34',
            date_uploaded_unix: 1639192954,
          },
        ],
        date_uploaded: '2021-12-11 01:15:05',
        date_uploaded_unix: 1639181705,
      },
      {
        id: 38440,
        url: 'https://yts.mx/movies/horse-latitudes-2020',
        imdb_code: 'tt8689270',
        title: 'Horse Latitudes',
        title_english: 'Horse Latitudes',
        title_long: 'Horse Latitudes (2020)',
        slug: 'horse-latitudes-2020',
        year: 2020,
        rating: 4.2,
        runtime: 104,
        genres: ['Drama'],
        summary:
          "Tom just turned thirty. She has spent her whole life chasing her wanderlust, and collecting passport stamps, experiences and stories to tell her grandchildren like many other people collect pay-stubs and stable relationships. Now faced with society's expectations of a woman in this chapter of her life, she arrives on a vineyard in the south of France to revisit the one man with whom she ever considered settling down. David has been in love with Tom since the first time he met her at a campfire on a beach in California, but he's spent the six years since she disappeared dedicating himself to the backbreaking art of making wine. When David decides to cancel all the plans he's ever made and pursue the relationship he's never been able to forget, Tom has to decide whether to commit to a conventional life or continue her life of adventure.",
        description_full:
          "Tom just turned thirty. She has spent her whole life chasing her wanderlust, and collecting passport stamps, experiences and stories to tell her grandchildren like many other people collect pay-stubs and stable relationships. Now faced with society's expectations of a woman in this chapter of her life, she arrives on a vineyard in the south of France to revisit the one man with whom she ever considered settling down. David has been in love with Tom since the first time he met her at a campfire on a beach in California, but he's spent the six years since she disappeared dedicating himself to the backbreaking art of making wine. When David decides to cancel all the plans he's ever made and pursue the relationship he's never been able to forget, Tom has to decide whether to commit to a conventional life or continue her life of adventure.",
        synopsis:
          "Tom just turned thirty. She has spent her whole life chasing her wanderlust, and collecting passport stamps, experiences and stories to tell her grandchildren like many other people collect pay-stubs and stable relationships. Now faced with society's expectations of a woman in this chapter of her life, she arrives on a vineyard in the south of France to revisit the one man with whom she ever considered settling down. David has been in love with Tom since the first time he met her at a campfire on a beach in California, but he's spent the six years since she disappeared dedicating himself to the backbreaking art of making wine. When David decides to cancel all the plans he's ever made and pursue the relationship he's never been able to forget, Tom has to decide whether to commit to a conventional life or continue her life of adventure.",
        yt_trailer_code: 't-reXmaiIvE',
        language: 'en',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/horse_latitudes_2020/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/horse_latitudes_2020/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/horse_latitudes_2020/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/horse_latitudes_2020/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/horse_latitudes_2020/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/0B0F3B84FD6BBB744DE87175407FF950487E9581',
            hash: '0B0F3B84FD6BBB744DE87175407FF950487E9581',
            quality: '720p',
            type: 'web',
            seeds: 61,
            peers: 24,
            size: '956.43 MB',
            size_bytes: 1002889544,
            date_uploaded: '2021-12-10 11:32:17',
            date_uploaded_unix: 1639132337,
          },
          {
            url: 'https://yts.mx/torrent/download/B7D4B86DD3DC92E10B4A81397212595B25DDAEE9',
            hash: 'B7D4B86DD3DC92E10B4A81397212595B25DDAEE9',
            quality: '1080p',
            type: 'web',
            seeds: 0,
            peers: 0,
            size: '1.92 GB',
            size_bytes: 2061584302,
            date_uploaded: '2021-12-10 12:33:10',
            date_uploaded_unix: 1639135990,
          },
        ],
        date_uploaded: '2021-12-10 11:32:17',
        date_uploaded_unix: 1639132337,
      },
      {
        id: 38439,
        url: 'https://yts.mx/movies/american-refugee-2021',
        imdb_code: 'tt14556184',
        title: 'American Refugee',
        title_english: 'American Refugee',
        title_long: 'American Refugee (2021)',
        slug: 'american-refugee-2021',
        year: 2021,
        rating: 3.5,
        runtime: 94,
        genres: ['Crime', 'Drama', 'Horror', 'Thriller'],
        summary:
          "Follows a family seeking shelter in their neighbor's bunker, when the American economy is in collapse, and the danger inside is greater than outside.",
        description_full:
          "Follows a family seeking shelter in their neighbor's bunker, when the American economy is in collapse, and the danger inside is greater than outside.",
        synopsis:
          "Follows a family seeking shelter in their neighbor's bunker, when the American economy is in collapse, and the danger inside is greater than outside.",
        yt_trailer_code: 'aGjReL9ByIA',
        language: 'en',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/american_refugee_2021/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/american_refugee_2021/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/american_refugee_2021/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/american_refugee_2021/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/american_refugee_2021/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/91C8A6A7A58AAD22A9B764D0C2F9B3B34A72B8A1',
            hash: '91C8A6A7A58AAD22A9B764D0C2F9B3B34A72B8A1',
            quality: '720p',
            type: 'web',
            seeds: 0,
            peers: 0,
            size: '865.19 MB',
            size_bytes: 907217469,
            date_uploaded: '2021-12-10 10:52:56',
            date_uploaded_unix: 1639129976,
          },
          {
            url: 'https://yts.mx/torrent/download/F71F345267E0EFF9B3E8182ACB5A056C9BD7BFC9',
            hash: 'F71F345267E0EFF9B3E8182ACB5A056C9BD7BFC9',
            quality: '1080p',
            type: 'web',
            seeds: 0,
            peers: 0,
            size: '1.74 GB',
            size_bytes: 1868310774,
            date_uploaded: '2021-12-10 13:04:32',
            date_uploaded_unix: 1639137872,
          },
        ],
        date_uploaded: '2021-12-10 10:52:56',
        date_uploaded_unix: 1639129976,
      },
      {
        id: 38438,
        url: 'https://yts.mx/movies/a-christmas-proposal-2021',
        imdb_code: 'tt14807078',
        title: 'A Christmas Proposal',
        title_english: 'A Christmas Proposal',
        title_long: 'A Christmas Proposal (2021)',
        slug: 'a-christmas-proposal-2021',
        year: 2021,
        rating: 0,
        runtime: 0,
        genres: ['Romance'],
        summary:
          "Chef who dreams of having own food trucks, agrees to pose as girlfriend of an attorney. Working together, they try to prove he's the ideal candidate to take over the family firm, but is complicated as real sparks begin to fly.",
        description_full:
          "Chef who dreams of having own food trucks, agrees to pose as girlfriend of an attorney. Working together, they try to prove he's the ideal candidate to take over the family firm, but is complicated as real sparks begin to fly.",
        synopsis:
          "Chef who dreams of having own food trucks, agrees to pose as girlfriend of an attorney. Working together, they try to prove he's the ideal candidate to take over the family firm, but is complicated as real sparks begin to fly.",
        yt_trailer_code: '',
        language: 'en',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/a_christmas_proposal_2021/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/a_christmas_proposal_2021/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/a_christmas_proposal_2021/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/a_christmas_proposal_2021/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/a_christmas_proposal_2021/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/27F712DC084DFFF52D24CA59DFB92A3339C66945',
            hash: '27F712DC084DFFF52D24CA59DFB92A3339C66945',
            quality: '720p',
            type: 'web',
            seeds: 58,
            peers: 21,
            size: '883.78 MB',
            size_bytes: 926710497,
            date_uploaded: '2021-12-10 09:58:01',
            date_uploaded_unix: 1639126681,
          },
          {
            url: 'https://yts.mx/torrent/download/08C46AC9E3FC199DBAAA9A54285248D0F8138912',
            hash: '08C46AC9E3FC199DBAAA9A54285248D0F8138912',
            quality: '1080p',
            type: 'web',
            seeds: 62,
            peers: 26,
            size: '1.6 GB',
            size_bytes: 1717986918,
            date_uploaded: '2021-12-10 10:57:48',
            date_uploaded_unix: 1639130268,
          },
        ],
        date_uploaded: '2021-12-10 09:58:01',
        date_uploaded_unix: 1639126681,
      },
      {
        id: 38437,
        url: 'https://yts.mx/movies/kanye-west-a-higher-power-2020',
        imdb_code: 'tt14586662',
        title: 'Kanye West: A Higher Power',
        title_english: 'Kanye West: A Higher Power',
        title_long: 'Kanye West: A Higher Power (2020)',
        slug: 'kanye-west-a-higher-power-2020',
        year: 2020,
        rating: 2.8,
        runtime: 0,
        genres: ['Documentary', 'Music'],
        summary:
          'Kanye West is one of the most recognizable rappers of the 21st century, transforming the sound of music through his production style and passionate lyrics. However, controversial statements would be a constant factor in his career, affecting his life and causing uproar around the pop-culture world. The past decade of his career has been turbulent, but he maintains his status as one of the greatest rappers of his generation.',
        description_full:
          'Kanye West is one of the most recognizable rappers of the 21st century, transforming the sound of music through his production style and passionate lyrics. However, controversial statements would be a constant factor in his career, affecting his life and causing uproar around the pop-culture world. The past decade of his career has been turbulent, but he maintains his status as one of the greatest rappers of his generation.',
        synopsis:
          'Kanye West is one of the most recognizable rappers of the 21st century, transforming the sound of music through his production style and passionate lyrics. However, controversial statements would be a constant factor in his career, affecting his life and causing uproar around the pop-culture world. The past decade of his career has been turbulent, but he maintains his status as one of the greatest rappers of his generation.',
        yt_trailer_code: '',
        language: 'en',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/kanye_west_a_higher_power_2020/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/kanye_west_a_higher_power_2020/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/kanye_west_a_higher_power_2020/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/kanye_west_a_higher_power_2020/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/kanye_west_a_higher_power_2020/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/BCAE6F7C2BC436C4A56D681F87CF117A5A53DAC2',
            hash: 'BCAE6F7C2BC436C4A56D681F87CF117A5A53DAC2',
            quality: '720p',
            type: 'web',
            seeds: 0,
            peers: 0,
            size: '531.05 MB',
            size_bytes: 556846285,
            date_uploaded: '2021-12-10 21:54:50',
            date_uploaded_unix: 1639169690,
          },
          {
            url: 'https://yts.mx/torrent/download/A0A78AB40CDDF0F8B2684C7E0DC1C70D10C08CD0',
            hash: 'A0A78AB40CDDF0F8B2684C7E0DC1C70D10C08CD0',
            quality: '1080p',
            type: 'web',
            seeds: 0,
            peers: 0,
            size: '985.84 MB',
            size_bytes: 1033728164,
            date_uploaded: '2021-12-10 23:37:42',
            date_uploaded_unix: 1639175862,
          },
        ],
        date_uploaded: '2021-12-10 21:54:50',
        date_uploaded_unix: 1639169690,
      },
      {
        id: 38436,
        url: 'https://yts.mx/movies/ricky-powell-the-individualist-2020',
        imdb_code: 'tt11905612',
        title: 'Ricky Powell: The Individualist',
        title_english: 'Ricky Powell: The Individualist',
        title_long: 'Ricky Powell: The Individualist (2020)',
        slug: 'ricky-powell-the-individualist-2020',
        year: 2020,
        rating: 7.8,
        runtime: 110,
        genres: ['Biography', 'Documentary'],
        summary:
          "Famed street photographer Ricky Powell made a name for himself taking wild portraits of New York City's who's who in the 80s and 90s. From the Beastie Boys to Basquiat, Powell's lens captured the grit and glamour of the city's downtown scene like never before. Powell and some of his notable subjects reflect on his fascinating life and work - as well as the demons that shaped him. —SHOWTIME",
        description_full:
          "Famed street photographer Ricky Powell made a name for himself taking wild portraits of New York City's who's who in the 80s and 90s. From the Beastie Boys to Basquiat, Powell's lens captured the grit and glamour of the city's downtown scene like never before. Powell and some of his notable subjects reflect on his fascinating life and work - as well as the demons that shaped him. —SHOWTIME",
        synopsis:
          "Famed street photographer Ricky Powell made a name for himself taking wild portraits of New York City's who's who in the 80s and 90s. From the Beastie Boys to Basquiat, Powell's lens captured the grit and glamour of the city's downtown scene like never before. Powell and some of his notable subjects reflect on his fascinating life and work - as well as the demons that shaped him. —SHOWTIME",
        yt_trailer_code: '',
        language: 'en',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/ricky_powell_the_individualist_2020/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/ricky_powell_the_individualist_2020/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/ricky_powell_the_individualist_2020/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/ricky_powell_the_individualist_2020/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/ricky_powell_the_individualist_2020/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/B0AD818CCE3A2FDF0D43F93315C8B308F3825316',
            hash: 'B0AD818CCE3A2FDF0D43F93315C8B308F3825316',
            quality: '720p',
            type: 'web',
            seeds: 0,
            peers: 0,
            size: '973.63 MB',
            size_bytes: 1020925051,
            date_uploaded: '2021-12-10 18:17:13',
            date_uploaded_unix: 1639156633,
          },
          {
            url: 'https://yts.mx/torrent/download/55186A493C1300EA07B9B78B42C848488064D844',
            hash: '55186A493C1300EA07B9B78B42C848488064D844',
            quality: '1080p',
            type: 'web',
            seeds: 0,
            peers: 0,
            size: '1.95 GB',
            size_bytes: 2093796557,
            date_uploaded: '2021-12-10 21:00:23',
            date_uploaded_unix: 1639166423,
          },
        ],
        date_uploaded: '2021-12-10 18:17:13',
        date_uploaded_unix: 1639156633,
      },
      {
        id: 38435,
        url: 'https://yts.mx/movies/mr-saturday-night-2021',
        imdb_code: 'tt15721532',
        title: 'Mr. Saturday Night',
        title_english: 'Mr. Saturday Night',
        title_long: 'Mr. Saturday Night (2021)',
        slug: 'mr-saturday-night-2021',
        year: 2021,
        rating: 6.8,
        runtime: 83,
        genres: ['Documentary'],
        summary:
          'The untold story of Robert Stigwood and how he amped the disco era.',
        description_full:
          'The untold story of Robert Stigwood and how he amped the disco era.',
        synopsis:
          'The untold story of Robert Stigwood and how he amped the disco era.',
        yt_trailer_code: '',
        language: 'en',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/mr_saturday_night_2021/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/mr_saturday_night_2021/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/mr_saturday_night_2021/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/mr_saturday_night_2021/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/mr_saturday_night_2021/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/BE469D78F9E8D9D1EB46819254C8175BADE5973F',
            hash: 'BE469D78F9E8D9D1EB46819254C8175BADE5973F',
            quality: '720p',
            type: 'web',
            seeds: 0,
            peers: 0,
            size: '756.83 MB',
            size_bytes: 793593774,
            date_uploaded: '2021-12-10 08:17:38',
            date_uploaded_unix: 1639120658,
          },
          {
            url: 'https://yts.mx/torrent/download/8FB334A72E11F2BBDA11BE620523239D005DACA0',
            hash: '8FB334A72E11F2BBDA11BE620523239D005DACA0',
            quality: '1080p',
            type: 'web',
            seeds: 0,
            peers: 0,
            size: '1.52 GB',
            size_bytes: 1632087572,
            date_uploaded: '2021-12-10 09:15:16',
            date_uploaded_unix: 1639124116,
          },
        ],
        date_uploaded: '2021-12-10 08:17:38',
        date_uploaded_unix: 1639120658,
      },
      {
        id: 38434,
        url: 'https://yts.mx/movies/famous-2021',
        imdb_code: 'tt10054778',
        title: 'Famous',
        title_english: 'Famous',
        title_long: 'Famous (2021)',
        slug: 'famous-2021',
        year: 2021,
        rating: 0,
        runtime: 110,
        genres: ['Drama'],
        summary:
          'Famous was filmed live on stage in the height of the #MeToo movement. Inspired by the lives of Young Hollywood stars like River Phoenix, Corey Feldman, Heath Ledger and Corey Haim, Famous takes you on a non-stop thrill ride behind the glamorous world of Young Hollywood and into the mind of A-list celebrity, Jason Mast. What appears to be a night of celebration for his first Oscar nomination, turns out to be an intricate plan to confront his past. Driven by a devastating need to expose the truth, Jason attempts to control the outcome of the evening and ignites a chain of events that pushes the boundaries of real friendship and reveals the true cost of fame. —Michael Leoni',
        description_full:
          'Famous was filmed live on stage in the height of the #MeToo movement. Inspired by the lives of Young Hollywood stars like River Phoenix, Corey Feldman, Heath Ledger and Corey Haim, Famous takes you on a non-stop thrill ride behind the glamorous world of Young Hollywood and into the mind of A-list celebrity, Jason Mast. What appears to be a night of celebration for his first Oscar nomination, turns out to be an intricate plan to confront his past. Driven by a devastating need to expose the truth, Jason attempts to control the outcome of the evening and ignites a chain of events that pushes the boundaries of real friendship and reveals the true cost of fame. —Michael Leoni',
        synopsis:
          'Famous was filmed live on stage in the height of the #MeToo movement. Inspired by the lives of Young Hollywood stars like River Phoenix, Corey Feldman, Heath Ledger and Corey Haim, Famous takes you on a non-stop thrill ride behind the glamorous world of Young Hollywood and into the mind of A-list celebrity, Jason Mast. What appears to be a night of celebration for his first Oscar nomination, turns out to be an intricate plan to confront his past. Driven by a devastating need to expose the truth, Jason attempts to control the outcome of the evening and ignites a chain of events that pushes the boundaries of real friendship and reveals the true cost of fame. —Michael Leoni',
        yt_trailer_code: 'rfy76sGcAlw',
        language: 'en',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/famous_2021/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/famous_2021/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/famous_2021/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/famous_2021/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/famous_2021/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/4BCCDD586A5C7C666BB815C6CF3C208057295F5B',
            hash: '4BCCDD586A5C7C666BB815C6CF3C208057295F5B',
            quality: '720p',
            type: 'web',
            seeds: 93,
            peers: 49,
            size: '1.06 GB',
            size_bytes: 1138166333,
            date_uploaded: '2021-12-10 07:01:33',
            date_uploaded_unix: 1639116093,
          },
          {
            url: 'https://yts.mx/torrent/download/5C2EE286DCA201DFFC8EC42893275A662BF416CA',
            hash: '5C2EE286DCA201DFFC8EC42893275A662BF416CA',
            quality: '1080p',
            type: 'web',
            seeds: 94,
            peers: 57,
            size: '2.18 GB',
            size_bytes: 2340757176,
            date_uploaded: '2021-12-10 08:28:17',
            date_uploaded_unix: 1639121297,
          },
        ],
        date_uploaded: '2021-12-10 07:01:33',
        date_uploaded_unix: 1639116093,
      },
      {
        id: 38433,
        url: 'https://yts.mx/movies/even-mice-belong-in-heaven-2021',
        imdb_code: 'tt3804810',
        title: 'Even Mice Belong in Heaven',
        title_english: 'Even Mice Belong in Heaven',
        title_long: 'Even Mice Belong in Heaven (2021)',
        slug: 'even-mice-belong-in-heaven-2021',
        year: 2021,
        rating: 7.4,
        runtime: 80,
        genres: ['Adventure', 'Animation', 'Comedy'],
        summary:
          'A film about two mortal enemies - a little Mouse and a Fox, who after an unfortunate accident, meet in animal heaven. They lose their natural instincts and become best friends. Their wish to stay together after they return to earth comes true, but they are reborn into opposite roles. Thanks to the power of friendship they can even overcome what seems to be impossible.',
        description_full:
          'A film about two mortal enemies - a little Mouse and a Fox, who after an unfortunate accident, meet in animal heaven. They lose their natural instincts and become best friends. Their wish to stay together after they return to earth comes true, but they are reborn into opposite roles. Thanks to the power of friendship they can even overcome what seems to be impossible.',
        synopsis:
          'A film about two mortal enemies - a little Mouse and a Fox, who after an unfortunate accident, meet in animal heaven. They lose their natural instincts and become best friends. Their wish to stay together after they return to earth comes true, but they are reborn into opposite roles. Thanks to the power of friendship they can even overcome what seems to be impossible.',
        yt_trailer_code: 'nUGZJh6AgSU',
        language: 'cs',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/even_mice_belong_in_heaven_2021/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/even_mice_belong_in_heaven_2021/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/even_mice_belong_in_heaven_2021/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/even_mice_belong_in_heaven_2021/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/even_mice_belong_in_heaven_2021/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/7F915AC9B4E2A77A47448B1E4D24C605E1B9A128',
            hash: '7F915AC9B4E2A77A47448B1E4D24C605E1B9A128',
            quality: '720p',
            type: 'web',
            seeds: 0,
            peers: 0,
            size: '803.95 MB',
            size_bytes: 843002675,
            date_uploaded: '2021-12-10 14:42:26',
            date_uploaded_unix: 1639143746,
          },
          {
            url: 'https://yts.mx/torrent/download/A408D88794FAFE41D2CF1C7230DFE0B3800C9AAD',
            hash: 'A408D88794FAFE41D2CF1C7230DFE0B3800C9AAD',
            quality: '1080p',
            type: 'web',
            seeds: 0,
            peers: 0,
            size: '1.61 GB',
            size_bytes: 1728724337,
            date_uploaded: '2021-12-10 16:52:55',
            date_uploaded_unix: 1639151575,
          },
        ],
        date_uploaded: '2021-12-10 14:42:26',
        date_uploaded_unix: 1639143746,
      },
      {
        id: 38432,
        url: 'https://yts.mx/movies/agnes-2021',
        imdb_code: 'tt11348542',
        title: 'Agnes',
        title_english: 'Agnes',
        title_long: 'Agnes (2021)',
        slug: 'agnes-2021',
        year: 2021,
        rating: 5.5,
        runtime: 93,
        genres: ['Drama', 'Horror'],
        summary:
          'Rumors of demonic possession at a religious convent prompts a church investigation into the strange goings-on among its nuns. A disaffected priest and his neophyte are confronted with temptation, bloodshed and a crisis of faith.',
        description_full:
          'Rumors of demonic possession at a religious convent prompts a church investigation into the strange goings-on among its nuns. A disaffected priest and his neophyte are confronted with temptation, bloodshed and a crisis of faith.',
        synopsis:
          'Rumors of demonic possession at a religious convent prompts a church investigation into the strange goings-on among its nuns. A disaffected priest and his neophyte are confronted with temptation, bloodshed and a crisis of faith.',
        yt_trailer_code: 'WEWQbBOFcz4',
        language: 'en',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/agnes_2021/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/agnes_2021/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/agnes_2021/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/agnes_2021/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/agnes_2021/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/F01628CE5E053948A5103DD5C2F73CE4AF379630',
            hash: 'F01628CE5E053948A5103DD5C2F73CE4AF379630',
            quality: '720p',
            type: 'web',
            seeds: 0,
            peers: 0,
            size: '850.31 MB',
            size_bytes: 891614659,
            date_uploaded: '2021-12-10 11:28:21',
            date_uploaded_unix: 1639132101,
          },
          {
            url: 'https://yts.mx/torrent/download/F0483E314C55EBC505651C672983A465DB2412B8',
            hash: 'F0483E314C55EBC505651C672983A465DB2412B8',
            quality: '1080p',
            type: 'web',
            seeds: 0,
            peers: 0,
            size: '1.71 GB',
            size_bytes: 1836098519,
            date_uploaded: '2021-12-10 13:34:24',
            date_uploaded_unix: 1639139664,
          },
        ],
        date_uploaded: '2021-12-10 11:28:21',
        date_uploaded_unix: 1639132101,
      },
      {
        id: 38430,
        url: 'https://yts.mx/movies/the-last-son-2021',
        imdb_code: 'tt1800393',
        title: 'The Last Son',
        title_english: 'The Last Son',
        title_long: 'The Last Son (2021)',
        slug: 'the-last-son-2021',
        year: 2021,
        rating: 6.9,
        runtime: 96,
        genres: ['Action', 'Drama', 'Western'],
        summary: 'An outlaw attempts to end his evil family line.',
        description_full: 'An outlaw attempts to end his evil family line.',
        synopsis: 'An outlaw attempts to end his evil family line.',
        yt_trailer_code: 'KilcySbvmP8',
        language: 'en',
        mpa_rating: 'R',
        background_image:
          'https://yts.mx/assets/images/movies/the_last_son_2021/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/the_last_son_2021/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/the_last_son_2021/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/the_last_son_2021/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/the_last_son_2021/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/A529368226AC19EA4DA815E24A28397CC01C9508',
            hash: 'A529368226AC19EA4DA815E24A28397CC01C9508',
            quality: '720p',
            type: 'web',
            seeds: 0,
            peers: 0,
            size: '902.45 MB',
            size_bytes: 946287411,
            date_uploaded: '2021-12-10 06:45:10',
            date_uploaded_unix: 1639115110,
          },
          {
            url: 'https://yts.mx/torrent/download/5B322DB6D56D01513E6C265F96A2DF1D0D81A79B',
            hash: '5B322DB6D56D01513E6C265F96A2DF1D0D81A79B',
            quality: '1080p',
            type: 'web',
            seeds: 613,
            peers: 173,
            size: '1.81 GB',
            size_bytes: 1943472701,
            date_uploaded: '2021-12-10 07:42:01',
            date_uploaded_unix: 1639118521,
          },
        ],
        date_uploaded: '2021-12-10 06:45:10',
        date_uploaded_unix: 1639115110,
      },
      {
        id: 38431,
        url: 'https://yts.mx/movies/the-hating-game-2021',
        imdb_code: 'tt8718158',
        title: 'The Hating Game',
        title_english: 'The Hating Game',
        title_long: 'The Hating Game (2021)',
        slug: 'the-hating-game-2021',
        year: 2021,
        rating: 6.8,
        runtime: 102,
        genres: ['Comedy', 'Romance'],
        summary:
          "As assistants to the co-CEOs of a publishing company, Lucy Hutton and Joshua Templeman sit across from each other every day - and they hate each other. Not dislike. Not begrudgingly tolerate. H-A-T-E. Lucy can't understand Josh's joyless, uptight approach to his job and refusal to smile, which is in stark contrast to her bright clothes, quirkiness, and effusive people-pleasing. Trapped in a shared office 5 days a week, they've become entrenched in an addictive, ridiculous never-ending game of one-upmanship. Lucy can't let Josh beat her at anything - especially when a huge new promotion to be Managing Director is up for grabs. They strike a deal that whoever does not get the promotion must quit. It's game-on - But as tensions reach boiling point and an innocent elevator ride turns into a steamy kiss, Lucy begins to realize just how fine a line there is between love and hate.",
        description_full:
          "As assistants to the co-CEOs of a publishing company, Lucy Hutton and Joshua Templeman sit across from each other every day - and they hate each other. Not dislike. Not begrudgingly tolerate. H-A-T-E. Lucy can't understand Josh's joyless, uptight approach to his job and refusal to smile, which is in stark contrast to her bright clothes, quirkiness, and effusive people-pleasing. Trapped in a shared office 5 days a week, they've become entrenched in an addictive, ridiculous never-ending game of one-upmanship. Lucy can't let Josh beat her at anything - especially when a huge new promotion to be Managing Director is up for grabs. They strike a deal that whoever does not get the promotion must quit. It's game-on - But as tensions reach boiling point and an innocent elevator ride turns into a steamy kiss, Lucy begins to realize just how fine a line there is between love and hate.",
        synopsis:
          "As assistants to the co-CEOs of a publishing company, Lucy Hutton and Joshua Templeman sit across from each other every day - and they hate each other. Not dislike. Not begrudgingly tolerate. H-A-T-E. Lucy can't understand Josh's joyless, uptight approach to his job and refusal to smile, which is in stark contrast to her bright clothes, quirkiness, and effusive people-pleasing. Trapped in a shared office 5 days a week, they've become entrenched in an addictive, ridiculous never-ending game of one-upmanship. Lucy can't let Josh beat her at anything - especially when a huge new promotion to be Managing Director is up for grabs. They strike a deal that whoever does not get the promotion must quit. It's game-on - But as tensions reach boiling point and an innocent elevator ride turns into a steamy kiss, Lucy begins to realize just how fine a line there is between love and hate.",
        yt_trailer_code: 'j3qBGOD4b4A',
        language: 'en',
        mpa_rating: 'R',
        background_image:
          'https://yts.mx/assets/images/movies/the_hating_game_2021/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/the_hating_game_2021/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/the_hating_game_2021/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/the_hating_game_2021/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/the_hating_game_2021/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/6B58F04CB50F31BB621AE658DD017FCBFD2D8A67',
            hash: '6B58F04CB50F31BB621AE658DD017FCBFD2D8A67',
            quality: '720p',
            type: 'web',
            seeds: 927,
            peers: 368,
            size: '941.26 MB',
            size_bytes: 986982646,
            date_uploaded: '2021-12-10 06:46:23',
            date_uploaded_unix: 1639115183,
          },
          {
            url: 'https://yts.mx/torrent/download/ED92FA2B139E7FF2F3851E5FEA3D847C98F38456',
            hash: 'ED92FA2B139E7FF2F3851E5FEA3D847C98F38456',
            quality: '1080p',
            type: 'web',
            seeds: 0,
            peers: 0,
            size: '1.89 GB',
            size_bytes: 2029372047,
            date_uploaded: '2021-12-10 07:45:20',
            date_uploaded_unix: 1639118720,
          },
        ],
        date_uploaded: '2021-12-10 06:46:23',
        date_uploaded_unix: 1639115183,
      },
      {
        id: 38428,
        url: 'https://yts.mx/movies/unusual-tales-1949',
        imdb_code: 'tt0206012',
        title: 'Unusual Tales',
        title_english: 'Unusual Tales',
        title_long: 'Unusual Tales (1949)',
        slug: 'unusual-tales-1949',
        year: 1949,
        rating: 6.3,
        runtime: 88,
        genres: ['Horror', 'Mystery'],
        summary:
          "A group of policemen look over three murder cases including a cutthroat that prays on young women, a madman that hid his deformed landlord's corpse in the floor, and a wine aficionado who buries his friend alive.",
        description_full:
          "A group of policemen look over three murder cases including a cutthroat that prays on young women, a madman that hid his deformed landlord's corpse in the floor, and a wine aficionado who buries his friend alive.",
        synopsis:
          "A group of policemen look over three murder cases including a cutthroat that prays on young women, a madman that hid his deformed landlord's corpse in the floor, and a wine aficionado who buries his friend alive.",
        yt_trailer_code: '',
        language: 'fr',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/unusual_tales_1949/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/unusual_tales_1949/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/unusual_tales_1949/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/unusual_tales_1949/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/unusual_tales_1949/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/4FC5F23592BD7184A27411D62AC8EF9CCACB52B8',
            hash: '4FC5F23592BD7184A27411D62AC8EF9CCACB52B8',
            quality: '720p',
            type: 'bluray',
            seeds: 35,
            peers: 11,
            size: '812.38 MB',
            size_bytes: 851842171,
            date_uploaded: '2021-12-10 01:53:09',
            date_uploaded_unix: 1639097589,
          },
          {
            url: 'https://yts.mx/torrent/download/8329D723E4617E8BF5C07C3984B19BFC83927148',
            hash: '8329D723E4617E8BF5C07C3984B19BFC83927148',
            quality: '1080p',
            type: 'bluray',
            seeds: 43,
            peers: 19,
            size: '1.47 GB',
            size_bytes: 1578400481,
            date_uploaded: '2021-12-10 02:51:21',
            date_uploaded_unix: 1639101081,
          },
        ],
        date_uploaded: '2021-12-10 01:53:09',
        date_uploaded_unix: 1639097589,
      },
      {
        id: 38429,
        url: 'https://yts.mx/movies/road-to-sampo-1975',
        imdb_code: 'tt0307406',
        title: 'Road to Sampo',
        title_english: 'Road to Sampo',
        title_long: 'Road to Sampo (1975)',
        slug: 'road-to-sampo-1975',
        year: 1975,
        rating: 6.7,
        runtime: 95,
        genres: ['Drama'],
        summary:
          "Going through a jail and a site of construction, a young laborer Young-Dal meets middle aged Mr. Jeong on his way to his hometown Sampo after ten years' absence. They become to know a waitress Baek-Hwa who runs away from a restaurant and then, they travel together. Arriving at the destination Kangcheon Station, Mr. Jeong is disappointed at the changes of the old village by building a hotel. Young-Datl and Mr. Jeong stay at Sampo not as the hometown but as the site of living. Baek-Hwa leaves Sampo with a ticket Young-Dal buys her with his last money.",
        description_full:
          "Going through a jail and a site of construction, a young laborer Young-Dal meets middle aged Mr. Jeong on his way to his hometown Sampo after ten years' absence. They become to know a waitress Baek-Hwa who runs away from a restaurant and then, they travel together. Arriving at the destination Kangcheon Station, Mr. Jeong is disappointed at the changes of the old village by building a hotel. Young-Datl and Mr. Jeong stay at Sampo not as the hometown but as the site of living. Baek-Hwa leaves Sampo with a ticket Young-Dal buys her with his last money.",
        synopsis:
          "Going through a jail and a site of construction, a young laborer Young-Dal meets middle aged Mr. Jeong on his way to his hometown Sampo after ten years' absence. They become to know a waitress Baek-Hwa who runs away from a restaurant and then, they travel together. Arriving at the destination Kangcheon Station, Mr. Jeong is disappointed at the changes of the old village by building a hotel. Young-Datl and Mr. Jeong stay at Sampo not as the hometown but as the site of living. Baek-Hwa leaves Sampo with a ticket Young-Dal buys her with his last money.",
        yt_trailer_code: '',
        language: 'ko',
        mpa_rating: '',
        background_image:
          'https://yts.mx/assets/images/movies/road_to_sampo_1975/background.jpg',
        background_image_original:
          'https://yts.mx/assets/images/movies/road_to_sampo_1975/background.jpg',
        small_cover_image:
          'https://yts.mx/assets/images/movies/road_to_sampo_1975/small-cover.jpg',
        medium_cover_image:
          'https://yts.mx/assets/images/movies/road_to_sampo_1975/medium-cover.jpg',
        large_cover_image:
          'https://yts.mx/assets/images/movies/road_to_sampo_1975/large-cover.jpg',
        state: 'ok',
        torrents: [
          {
            url: 'https://yts.mx/torrent/download/6E3BBA24DD2979E0A31705D1137C971E96C5F7F9',
            hash: '6E3BBA24DD2979E0A31705D1137C971E96C5F7F9',
            quality: '720p',
            type: 'bluray',
            seeds: 32,
            peers: 24,
            size: '916.35 MB',
            size_bytes: 960862618,
            date_uploaded: '2021-12-10 03:36:49',
            date_uploaded_unix: 1639103809,
          },
          {
            url: 'https://yts.mx/torrent/download/B5BE34C6E34C038230D6501B6D4883B155A17B6E',
            hash: 'B5BE34C6E34C038230D6501B6D4883B155A17B6E',
            quality: '1080p',
            type: 'bluray',
            seeds: 48,
            peers: 24,
            size: '1.67 GB',
            size_bytes: 1793148846,
            date_uploaded: '2021-12-10 04:40:56',
            date_uploaded_unix: 1639107656,
          },
        ],
        date_uploaded: '2021-12-10 03:36:49',
        date_uploaded_unix: 1639103809,
      },
    ],
  },
  '@meta': {
    server_time: 1639207037,
    server_timezone: 'CET',
    api_version: 2,
    execution_time: '0.01 ms',
  },
};
